### ISSUE TITLE
Incorrect behavior if init keenSlider on display:none element

### ISSUE THREAD

**Issue by stepanO** [rcbyr/keen-slider#99]
Hi! I'm facing a problem with sliders which are initialized when the carousel element is non visible (display: none).

https://codesandbox.io/s/naughty-knuth-jx1bh?file=/index.html
![image](https://user-images.githubusercontent.com/7386436/111169089-b5c29300-85b3-11eb-817d-4d684f22dff2.png)

**Comment by stepanO** [comment]
I have fixed it with using IntersectionObserver and initializing the keen-slider when element become visible

` const options = {
            root: null,
            rootMargin: '0px',
            threshold: 0.0
        };
        this.observer = new IntersectionObserver(() => {
            if (this.offsetHeight) {
                new KeenSlider(slideWrapper, this.getOptions());
                this.observer.disconnect();
            }
        }, options);
        this.observer.observe(this);`

**Comment by stepanO** [comment]
I found another problem, by event **resize** the "hidden" carousels become broken, they are not response on any actions and method "details" return object with NaN values.

I have just one idea for fix it, I will destroy the hidden carousel and reinit it if it become visible

**Comment by rcbyr** [comment]
Sorry for the late reply. The way was right to use the refresh/resize function. But there was a bug. I have fixed this in the new version. Here it would be the update function that needs to be called.

**Comment by timfuhrmann** [comment]
What's the best practice for 6.6.2 since the refresh/resize function has been removed? Some of our sliders have `display: none` for desktop and are still broken on resize for mobile consequently. `slider.update` doesn't seem to do the trick.

**Comment by rcbyr** [comment]
Hello @timfuhrmann 

I couldn't reproduce that. Can you give me an code example or codesandbox that show this behavior?

**Comment by timfuhrmann** [comment]
@rcbyr Here's a minimal reproduction: https://codesandbox.io/s/suspicious-grothendieck-09zi2 

Increase the preview window's size until the slider disappears, hit the sandbox' preview reload button, resize it until it appears again, slider should be broken throwing the following TypeError:

> Cannot read properties of undefined (reading 'portion')

**Comment by rcbyr** [comment]
@timfuhrmann 

Thanks you very much! I fixed this in v6.6.3.
